language: python
python:
  # - "2.6" # deprecated version of python
  - "2.7"
  # - "3.3" # deprecated version of python not supported by pytest
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pytest
  - pip install .
# command to run tests
script:
  - pytest